# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12332f2b93bce6054f5b0f9ed546020d75934caea468bea783c2d887957be5ded4a084aebc4fd8e24e3f478600e8f76396a3d9c42ed787109767b8936c4e9915

test:
  secret_key_base: dd04dd2cb5caacfe6316ea29fe98f1aef011ca0c4c9be3b93f4059ad4137114ebce0d704f38383dda77567f8af8a75e502d485a17d9ea22949a92799e3c9c900

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
